import os from 'os';
import path from 'path';
process.env.PINOVA_DATA_DIR = path.join(os.tmpdir(), 'pinova_edu_safety_' + Date.now());
import { EducationRepository } from '../src/server/db/repositories/EducationRepository';
import { getTaxonomyByCountry } from '../src/data/educationTaxonomyData';
import { SEED_STUDENTS, SEED_CHILDREN_SUMMARIES, SEED_INVOICES, SEED_RECEIPTS, SEED_PAYMENTS, SEED_ADMISSION_APPLICATIONS, SEED_SCHOLARSHIPS, SEED_MARKETPLACE_ITEMS, SEED_PARENT_USER_ID } from '../src/data/educationSeedData';
const ok=(v:boolean,n:string)=>{if(!v) throw new Error('FAILED: '+n); console.log('[PASS] '+n);};
async function run(){
 const repo=new EducationRepository();
 ok(SEED_STUDENTS.length===0,'no seeded students');
 ok(SEED_CHILDREN_SUMMARIES.length===0,'no seeded guardian records');
 ok(SEED_INVOICES.length===0,'no seeded invoices');
 ok(SEED_RECEIPTS.length===0,'no seeded receipts');
 ok(SEED_PAYMENTS.length===0,'no seeded payments');
 ok(SEED_ADMISSION_APPLICATIONS.length===0,'no seeded admissions');
 ok(SEED_SCHOLARSHIPS.length===0,'no seeded scholarships');
 ok(SEED_MARKETPLACE_ITEMS.length===0,'no seeded marketplace items');
 ok(SEED_PARENT_USER_ID==='','no seeded guardian identity');
 ok(repo.getInstitutions().length>0,'global institution registry is loaded');
 ok(repo.getInvoices().length===0,'invoice repository starts empty');
 ok(repo.getScholarships().length===0,'scholarship repository starts empty');
 ok(repo.getStudentsByGuardian('authenticated-user').length===0,'student lookup fails closed');
 ok(getTaxonomyByCountry('NG')?.countryCode==='NG','Nigeria taxonomy configured');
 ok(getTaxonomyByCountry('ZZ')===null,'unsupported taxonomy fails closed');
 ok(getTaxonomyByCountry('')===null,'missing taxonomy fails closed');
 const totals=EducationRepository.calculateInvoiceTotals({subtotal:100,compulsoryFees:25,optionalFees:10,discount:5,scholarship:10,tax:0});
 ok(totals.totalAmount===120,'invoice calculation remains deterministic');
 console.log('Education production safety suite: GREEN');
}
run().catch(e=>{console.error(e);process.exit(1);});
