import { StorageEngine } from '../StorageEngine';
import { PstpAuditLogEntity } from '../types';

/** Append-only PSTP audit persistence. Production starts empty; every entry is generated by an authoritative server workflow. */
export class PstpAuditRepository {
  private engine: StorageEngine<PstpAuditLogEntity>;

  constructor() {
    this.engine = new StorageEngine<PstpAuditLogEntity>('pstp_audit_logs', 'id', []);
  }

  public appendLog(entry: Omit<PstpAuditLogEntity, 'id' | 'timestamp'> & { id?: string; timestamp?: string }): PstpAuditLogEntity {
    const log: PstpAuditLogEntity = {
      id: entry.id || `LOG-UUID-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
      orderId: entry.orderId,
      paymentId: entry.paymentId,
      actor: entry.actor || 'system',
      actorRole: entry.actorRole || 'system',
      action: entry.action || 'AUDIT_EVENT',
      details: entry.details || 'PSTP Security Audit Log Entry',
      ipAddress: entry.ipAddress || 'server',
      deviceInfo: entry.deviceInfo || 'PiNova PSTP Server',
      timestamp: entry.timestamp || new Date().toISOString()
    };
    this.engine.unshift(log);
    return log;
  }

  public getAll(): PstpAuditLogEntity[] { return this.engine.getAll(); }
  public findByOrderId(orderId: string): PstpAuditLogEntity[] { return this.engine.filter((l) => l.orderId === orderId); }
  public findByPaymentId(paymentId: string): PstpAuditLogEntity[] { return this.engine.filter((l) => l.paymentId === paymentId); }
  public count(): number { return this.engine.count(); }
}
