import type { Order } from '../../types';
import { getNeonSql, neonDatabaseEnabled } from '../db/NeonDatabase';
import { piDecimalForStorage } from './piDecimal';
export function durableOrderStorageEnabled(){return neonDatabaseEnabled();}
function rowToOrder(row:any):Order{const data:any={...(row?.data||{})};if(typeof data.totalPi==='string')data.totalPi=Number(data.totalPi);if(Array.isArray(data.items))data.items=data.items.map((item:any)=>({...item,product:item?.product&&typeof item.product.pricePi==='string'?{...item.product,pricePi:Number(item.product.pricePi),variants:Array.isArray(item.product.variants)?item.product.variants.map((v:any)=>typeof v?.priceDeltaPi==='string'?{...v,priceDeltaPi:Number(v.priceDeltaPi)}:v):item.product.variants}:item?.product}));return data as Order;}
function storageSnapshot(order:Order){const data:any=JSON.parse(JSON.stringify(order));data.totalPi=piDecimalForStorage(order.totalPi);if(Array.isArray(data.items))data.items=data.items.map((item:any)=>({...item,product:item?.product&&typeof item.product.pricePi==='number'?{...item.product,pricePi:piDecimalForStorage(item.product.pricePi),variants:Array.isArray(item.product.variants)?item.product.variants.map((v:any)=>typeof v?.priceDeltaPi==='number'?{...v,priceDeltaPi:piDecimalForStorage(v.priceDeltaPi)}:v):item.product.variants}:item?.product}));return data;}
export async function getDurableOrder(id:string):Promise<Order|null>{if(!id?.trim()||!neonDatabaseEnabled())return null;const sql=getNeonSql();const rows=(await sql`SELECT data FROM orders WHERE id=${id.trim()} AND is_deleted=FALSE LIMIT 1`) as unknown as Array<Record<string, any>>;return rows.length?rowToOrder(rows[0]):null;}
export async function listDurableOrders(buyerUsername?:string):Promise<Order[]>{if(!neonDatabaseEnabled())return[];const sql=getNeonSql();const rows=(buyerUsername?await sql`SELECT data FROM orders WHERE is_deleted=FALSE AND buyer_username=${buyerUsername} ORDER BY created_at DESC`:await sql`SELECT data FROM orders WHERE is_deleted=FALSE ORDER BY created_at DESC`) as unknown as Array<Record<string, any>>;return rows.map(rowToOrder);}
export async function softDeleteDurableOrder(id:string):Promise<Order|null>{const p=await getDurableOrder(id);if(!p)return null;return saveDurableOrder({...p,isDeleted:true});}
export async function saveDurableOrder(order:Order):Promise<Order>{if(!neonDatabaseEnabled())throw new Error('DURABLE_ORDER_STORAGE_UNAVAILABLE');const existing=await getDurableOrder(order.id);const expectedUpdatedAt=existing?.updatedAt??null;const now=new Date().toISOString();const p:Order={...order,buyerUsername:String(order.buyerUsername||'').trim(),totalPi:Number(order.totalPi),items:Array.isArray(order.items)?order.items:[],timeline:Array.isArray(order.timeline)?order.timeline:[],isDeleted:order.isDeleted??false,createdAt:existing?.createdAt??order.createdAt??now,updatedAt:now};if(!p.id||!p.buyerUsername)throw new Error('ORDER_ID_AND_BUYER_REQUIRED');if(!Number.isFinite(p.totalPi)||p.totalPi<0)throw new Error('INVALID_ORDER_TOTAL');if(!p.items.length)throw new Error('ORDER_ITEMS_REQUIRED');const sql=getNeonSql();const totalPiDb=piDecimalForStorage(p.totalPi);const data=JSON.stringify(storageSnapshot(p));const rows=await sql`INSERT INTO orders(id,buyer_username,total_pi,escrow_status,pstp_status,pi_payment_id,pi_txid,server_verified,tracking_number,carrier,is_deleted,data,created_at,updated_at) VALUES(${p.id},${p.buyerUsername},${totalPiDb},${p.escrowStatus},${p.pstpStatus},${p.piPaymentId||null},${p.piTxid||null},${p.serverVerified===true},${p.trackingNumber||null},${p.carrier||null},${p.isDeleted},${data}::jsonb,${p.createdAt},${p.updatedAt}) ON CONFLICT(id) DO UPDATE SET buyer_username=EXCLUDED.buyer_username,total_pi=EXCLUDED.total_pi,escrow_status=EXCLUDED.escrow_status,pstp_status=EXCLUDED.pstp_status,pi_payment_id=EXCLUDED.pi_payment_id,pi_txid=EXCLUDED.pi_txid,server_verified=EXCLUDED.server_verified,tracking_number=EXCLUDED.tracking_number,carrier=EXCLUDED.carrier,is_deleted=EXCLUDED.is_deleted,data=EXCLUDED.data,updated_at=EXCLUDED.updated_at WHERE orders.updated_at=${expectedUpdatedAt} RETURNING id`;if(!rows.length)throw new Error('ORDER_WRITE_CONFLICT');return p;}
export async function markDurableOrderPaymentVerified(id:string,piPaymentId:string,piTxid?:string):Promise<Order|null>{const p=await getDurableOrder(id);if(!p||p.isDeleted)return null;if(!piPaymentId.trim())throw new Error('PI_PAYMENT_ID_REQUIRED');const timestamp=new Date().toISOString();return saveDurableOrder({...p,piPaymentId:piPaymentId.trim(),piTxid:piTxid?.trim()||p.piTxid,serverVerified:true,pstpStatus:'Payment Verified',escrowStatus:'approved',updatedAt:timestamp,timeline:[...p.timeline,{status:'Payment Verified',timestamp,actor:'system',actorRole:'system',note:'Pi payment server-verified; order may proceed to PSTP protection.'}]});}
