import type { Product, ProductCategory, AvailabilityStatus } from '../../types';
import { getNeonSql, neonDatabaseEnabled } from '../db/NeonDatabase';

function normalize(product: Product, existing?: Product): Product {
  const now = new Date().toISOString();
  const p: Product = {...product,title:String(product.title||'').trim(),description:String(product.description||'').trim(),sellerId:String(product.sellerId||'').trim(),sellerName:String(product.sellerName||'').trim(),sellerDisplayName:String(product.sellerDisplayName||'').trim()||undefined,images:Array.isArray(product.images)?product.images.filter(Boolean):[],features:Array.isArray(product.features)?product.features.filter(Boolean):[],tags:Array.isArray(product.tags)?product.tags.filter(Boolean):[],isActive:product.isActive??false,isDeleted:product.isDeleted??false,moderationStatus:product.moderationStatus??'PENDING_REVIEW',createdAt:existing?.createdAt??product.createdAt??now,updatedAt:now};
  if(!p.id||!p.sellerId||!p.title)throw new Error('PRODUCT_ID_SELLER_ID_AND_TITLE_REQUIRED');
  if(!Number.isFinite(p.pricePi)||p.pricePi<0)throw new Error('INVALID_PRODUCT_PRICE');
  if(!Number.isInteger(p.stock)||p.stock<0)throw new Error('INVALID_PRODUCT_STOCK');
  return p;
}
function rowToProduct(row:any):Product{return(row?.data||{})as Product;}
export function durableProductStorageEnabled(){return neonDatabaseEnabled();}
export async function getDurableProduct(id:string):Promise<Product|null>{if(!id?.trim()||!neonDatabaseEnabled())return null;const sql=getNeonSql();const rows=await sql`SELECT data FROM products WHERE id=${id.trim()} AND is_deleted=FALSE LIMIT 1`;return rows.length?rowToProduct(rows[0]):null;}
export async function listDurableProducts(options?:{includeDeleted?:boolean;activeOnly?:boolean;sellerId?:string;category?:ProductCategory;q?:string;}):Promise<Product[]>{if(!neonDatabaseEnabled())return[];const sql=getNeonSql();const rows=options?.includeDeleted?await sql`SELECT data FROM products ORDER BY created_at DESC`:await sql`SELECT data FROM products WHERE is_deleted=FALSE ORDER BY created_at DESC`;const q=String(options?.q||'').trim().toLowerCase();return rows.map(rowToProduct).filter(p=>{if(options?.activeOnly&&p.isActive!==true)return false;if(options?.sellerId&&p.sellerId!==options.sellerId)return false;if(options?.category){const c=String(options.category).trim().toLowerCase();if(String(p.marketplaceCategory||'').trim().toLowerCase()!==c&&String(p.category||'').trim().toLowerCase()!==c)return false;}if(q&&! [p.title,p.description,p.subcategory,p.sellerName,...(p.features||[]),...(p.tags||[])].join(' ').toLowerCase().includes(q))return false;return true;});}
export async function saveDurableProduct(product:Product):Promise<Product>{if(!neonDatabaseEnabled())throw new Error('DURABLE_PRODUCT_STORAGE_UNAVAILABLE');const existing=await getDurableProduct(product.id);const p=normalize(product,existing||undefined);const sql=getNeonSql();const data=JSON.stringify(p);await sql`INSERT INTO products(id,seller_id,title,marketplace_category,category,price_pi,stock,availability_status,is_active,is_deleted,moderation_status,data,created_at,updated_at) VALUES(${p.id},${p.sellerId},${p.title},${p.marketplaceCategory||null},${p.category||null},${p.pricePi},${p.stock},${p.availabilityStatus||null},${p.isActive},${p.isDeleted},${p.moderationStatus},${data}::jsonb,${p.createdAt},${p.updatedAt}) ON CONFLICT(id) DO UPDATE SET seller_id=EXCLUDED.seller_id,title=EXCLUDED.title,marketplace_category=EXCLUDED.marketplace_category,category=EXCLUDED.category,price_pi=EXCLUDED.price_pi,stock=EXCLUDED.stock,availability_status=EXCLUDED.availability_status,is_active=EXCLUDED.is_active,is_deleted=EXCLUDED.is_deleted,moderation_status=EXCLUDED.moderation_status,data=EXCLUDED.data,updated_at=EXCLUDED.updated_at`;return p;}
export async function updateDurableProductAvailability(id:string,status:AvailabilityStatus,stock:number):Promise<Product|null>{if(!Number.isInteger(stock)||stock<0)throw new Error('INVALID_PRODUCT_STOCK');const p=await getDurableProduct(id);if(!p||p.isDeleted)return null;return saveDurableProduct({...p,stock,availabilityStatus:status,isActive:status!=='out_of_stock'&&p.isActive!==false});}
export async function softDeleteDurableProduct(id:string):Promise<boolean>{const p=await getDurableProduct(id);if(!p)return false;await saveDurableProduct({...p,isDeleted:true,isActive:false});return true;}
export async function reserveDurableProductStockBatch(requests:Array<{id:string;quantity:number}>):Promise<Product[]|undefined>{if(!neonDatabaseEnabled())throw new Error('DURABLE_PRODUCT_STORAGE_UNAVAILABLE');const merged=new Map<string,number>();for(const r of requests){if(!r.id||!Number.isInteger(r.quantity)||r.quantity<1)throw new Error('INVALID_STOCK_RESERVATION_QUANTITY');merged.set(r.id,(merged.get(r.id)||0)+r.quantity);}const reserved:Product[]=[];for(const[id,qty]of merged){const p=await getDurableProduct(id);if(!p||p.isDeleted||p.isActive!==true)return undefined;if(p.fulfillmentType==='digital_download'||p.fulfillmentType==='instant_key'){reserved.push(p);continue;}const sql=getNeonSql();const rows=await sql`UPDATE products SET stock=stock-${qty},availability_status=CASE WHEN stock-${qty}<=0 THEN 'out_of_stock' ELSE availability_status END,is_active=CASE WHEN stock-${qty}>0 THEN is_active ELSE FALSE END,updated_at=NOW(),data=jsonb_set(jsonb_set(data,'{stock}',to_jsonb(stock-${qty}),true),'{availabilityStatus}',to_jsonb(CASE WHEN stock-${qty}<=0 THEN 'out_of_stock' ELSE availability_status END),true) WHERE id=${id} AND is_deleted=FALSE AND is_active=TRUE AND stock>=${qty} RETURNING data`;if(!rows.length)throw new Error('INSUFFICIENT_STOCK');reserved.push(rowToProduct(rows[0]));}return reserved;}
export async function deleteDurableProductBlob(id:string){return softDeleteDurableProduct(id);}
